export const TODO_CREATE = "TODO_CREATE";
export const TODO_CREATE_LOADING = "TODO_CREATE_LOADING";
export const TODO_CREATE_ERROR = "TODO_CREATE_ERROR";

export const TODO_UPDATE = "TODO_UPDATE";
export const TODO_UPDATE_LOADING = "TODO_UPDATE_LOADING";
export const TODO_UPDATE_ERROR = "TODO_UPDATE_ERROR";

export const TODO_GET = "TODO_GET";
export const TODO_GET_LOADING = "TODO_GET_LOADING";
export const TODO_GET_ERROR = "TODO_GET_ERROR";

export const TODO_DELETE = "TODO_DELETE";
export const TODO_DELETE_LOADING = "TODO_DELETE_LOADING";
export const TODO_DELETE_ERROR = "TODO_DELETE_ERROR";

export const TODO_CHECK = "TODO_CHECK";
export const TODO_CHECK_LOADING = "TODO_CHECK_LOADING";
export const TODO_CHECK_ERROR = "TODO_CHECK_ERROR";